"""Add DVC fields to MLModel table.

Revision ID: 8a1b2c3d4e5f
Revises: 7f9a871a5688
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8a1b2c3d4e5f"
down_revision = "7f9a871a5688"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ml_model", sa.Column("dataset_dvc_hash", sa.String(), nullable=True))
    op.add_column(
        "ml_model", sa.Column("dataset_dvc_registry_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ml_model", "dataset_dvc_registry_name")
    op.drop_column("ml_model", "dataset_dvc_hash")
    # ### end Alembic commands ###
