"""Script template for Alembic migration files."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093422de8ff9'
down_revision: str | None = '5d2569ec5ad0'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant', sa.Column('max_datasets', sa.Integer(), nullable=True))
    op.add_column('tenant', sa.Column('max_models', sa.Integer(), nullable=True))
    op.add_column('tenant', sa.Column('max_predictions_per_day', sa.Integer(), nullable=True))
    op.add_column('tenant', sa.Column('max_training_jobs_per_day', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant', 'max_training_jobs_per_day')
    op.drop_column('tenant', 'max_predictions_per_day')
    op.drop_column('tenant', 'max_models')
    op.drop_column('tenant', 'max_datasets')
    # ### end Alembic commands ###
