"""Script template for Alembic migration files."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9a871a5688'
down_revision: str | None = 'b6ea64ce31c2'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('dataset', 'is_dvc_tracked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.drop_column('dataset', 'dvc_commit_hash')
    op.alter_column('ml_model', 'mlflow_version',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('ml_model', 'version',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ml_model', 'stage',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ml_model', 'stage',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Staging'::character varying"),
               existing_nullable=False)
    op.alter_column('ml_model', 'version',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'1.0.0'::character varying"),
               existing_nullable=False)
    op.alter_column('ml_model', 'mlflow_version',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.add_column('dataset', sa.Column('dvc_commit_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('dataset', 'is_dvc_tracked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_column('dataset', 'is_active')
    # ### end Alembic commands ###
